### ISSUE TITLE
Wordpress 4.6.1, the plugin doesnt create "wp-content/files" folder

### ISSUE THREAD

**Issue by SPGStudio** [lesterchan/wp-downloadmanager#18]

**Comment by lesterchan** [comment]
Might be the plugin doesn't have permission aka no writable permisssion to create it. Then just create it?

**Comment by SPGStudio** [comment]
wp-content folder is 755

i didnt change it since the install of wordpress 

im just informing you of the issue

i created the folder files manually and i could upload files

**Comment by lesterchan** [comment]
755 doesn't mean anything if the owner of the folder and the web process is not the same. If the folder is owned by root and your web process is something else, 755 is not writable as well. One thing for sure 777 is writable by all and it works. Normally Apache has this problem.

If you are on nginx, www-data:www-data is used for the process and check if your folder is owned by www-data.
