### ISSUE TITLE
stream_limit not working on wp4.7.4

### ISSUE THREAD

**Issue by frkinta** [lesterchan/wp-downloadmanager#22]
I've  insert the following code to my website: `[page_download category="2" stream_limit="5"]`. I have all the files on my page instead of only 5

_wp4.7.4_

**Comment by lesterchan** [comment]
stream_limit was never working for page_download because the variable was not in it.

Check our the General Usage https://github.com/lesterchan/wp-downloadmanager, the shortcode is [download].
