### ISSUE TITLE
Current date and time not populated when adding files

### ISSUE THREAD

**Issue by jishac** [lesterchan/wp-downloadmanager#24]
The current date is not automatically populated when adding a new file.  Instead Jan 1, 2000 is selected.

This seems to be an issue with types and the function "file_timestamp" in "wp-downloadmanager.php".  gmdate returns strings and is being compared to integers for the selection causing the === to fail.

Suggest altering the code to either cast the assignments of day, month2, etc to int or replacing the === with ==

**Comment by lesterchan** [comment]
Thanks for the report. Let me know if the above fixes it.

**Comment by jishac** [comment]
It does correct the issue.
