### ISSUE TITLE
categories don't works correctly

### ISSUE THREAD

**Issue by StefSoge** [lesterchan/wp-downloadmanager#31]
it would appear that the categories textarea, in the options form, no longer passes the newline \ n

**Comment by lesterchan** [comment]
Can you overwrite download-options.php with https://raw.githubusercontent.com/lesterchan/wp-downloadmanager/master/download-options.php and see if it fixes the problem.

**Comment by StefSoge** [comment]
Hi Lester,

same behavior with the modified script ...

I also tried to manually update the categories but, in this case, the textarea of the options form is empty ...

UPDATE `wp_options` SET` option_value` = 'a: 2: {i: 0; s: 0: \ "\"; i: 1; s: 280: \ "Black on White \ r \ nNormativa \ r \ nBrochures \ r \ nPiano del Parco \ r \ nProgrammatic Conference \ r \ nTrails \ r \ nForms \ r \ n Calls \ r \ nProjects \ r \ nActive Parks 2011/12 \ r \ nFaunistic control \ r \ nMultimedia \ r \ nPUC3 - 2013 \ r \ nQSV - 2013 \ r \ nVAS Piano Nera 2015 \ r \ nAnnual reports \ r \ nCompetitions \ r \ nContributions \ r \ nThe voice of CIAV \ r \ nNAHAR - CIAV APS \ ";} 'WHERE` wp_options `. option_id` = 429;

will anything have changed in the way browsers handle the POST array? 

regards

**Comment by StefSoge** [comment]
All OK with modified script !   thanks ...
